### ISSUE TITLE
Please cut a patch release with the missing semi-colon.

### ISSUE THREAD

**Issue by jcdyer** [james-darkfox/rs-scoped_log#6]
Can you release a 0.1.1 version to crates.io with the commit that includes the missing semicolon?  The warnings are an ongoing aggravation when trying to develop in a library that includes scoped_log.

**Comment by james-darkfox** [comment]
@jcdyer Hello. Sorry for the inconvenience. I was just about to archive this repository because it isn't maintained. Do you still use this crate? If so, I recommend looking into the alternatives. I haven't played with slog yet but it looks like at least one viable option.

https://docs.rs/slog-scope/4.0.1/slog_scope/

I just `cargo test`'d the crate and it doesn't even build. :skull:

**Comment by jcdyer** [comment]
Nah.  Go ahead.  I was contributing to another library that used it.  Those days are long gone now.  Go ahead and archive it.

**Comment by james-darkfox** [comment]
Done
